config/routes.rb
Ticketee::Application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :projects do
        resources :tickets
      end
    end
  end

  namespace :api do
    namespace :v2 do
      resources :projects do
        resources :tickets
      end
    end
  end
  
  get "users/index"
  devise_for :users, controllers: { registrations: "registrations", omniauth_callbacks: "users/omniauth_callbacks" }
  get "/awaiting_confirmation", to: "users#confirmation", as: "confirm_user"
  put "/admin/users/:user_id/permissions", to: "admin/permissions#update", as: "update_user_permissions"
  delete "/projects/:project_id/tickets/:id/tags/:tag_name", to: "tickets#remove_tag", as: "remove_tag_ticket" 

  root 'projects#index'
  resources :projects do
    resources :tickets
  end

  resources :tickets do
    resources :comments
  end

  namespace :admin do
    root :to => "base#index"
    resources :users do
      resources :permissions
    end
    resources :states do
      member do
        get :make_default
      end
    end
  end

  resources :files

end

app/models/permission.rb
class Permission < ActiveRecord::Base
  belongs_to :user
  belongs_to :thing, polymorphic: true
end

app/controllers/admin/permissions_controller.rb
class Admin::PermissionsController < Admin::BaseController
  before_action :find_user

  def index
    @ability = Ability.new(@user)
    @projects = Project.all
  end

  def update
    @user.permissions.clear
    params[:permissions].each do |id, permissions|
      project = Project.find(id)
      permissions.each do |permission, checked|
        Permission.create!(user: @user, thing: project, action: permission)
      end
    end
    flash[:notice] = "Permissions updated."
    redirect_to admin_user_permissions_path
  end

  private
  def find_user
    @user = User.find(params[:user_id])
  end
end

app/helpers/admin/permissions_helper.rb
module Admin::PermissionsHelper
  def permissions
    {
      "view" => "View",
      "create tickets" => "Create Tickets",
      "update tickets" => "Update Tickets",
      "delete tickets" => "Delete Tickets",
      "change states" => "Change States"
    }
  end
end

app/views/admin/permissions/index.html.erb
<h2>Permissions for <%= @user.display_name %></h2>
<%= form_tag update_user_permissions_path, method: :put do %>
  <table>
    <thead>
      <th>Project</th>
      <% permissions.each do |name, text| %>
        <th><%= text %></th>
      <% end %>
    </thead>
    <tbody>
      <% @projects.each do |project| %>
        <tr class='<%= cycle("odd", "even") %>'>
          <td><%= project.name %></td>
          <% permissions.each do |name, text| %>
            <td>
              <%= check_box_tag "permissions[#{project.id}][#{name}]", @ability.can?(name.to_sym, project) %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= submit_tag "Update" %>
<% end %>